[project]
name = "greg"
version = "0.4.9"
description = "A command-line podcast aggregator"
readme = "README.md"
authors = [
    { name = "Manolo Martínez", email = "manolo@austrohungaro.com" },
]
license = "GPL-3.0-only"
requires-python = ">=3.13,<3.14"
dependencies = [
    "feedparser",
    "requests",
	"eyeD3",
	"beautifulsoup4", 
	"lxml"
]

[project.scripts]
greg = "greg.parser:main"

[project.urls]
Homepage = "https://github.com/manolomartinez/greg"
Repository = "https://github.com/manolomartinez/greg"

[build-system]
requires = ["uv-build"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-name = "greg"
module-root = ""

[dependency-groups]
dev = [
    "pytest>=9.0",
]
